# Generated by Django 4.1 on 2023-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="age",
            field=models.IntegerField(default=0, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(max_length=120, verbose_name="First_Name"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(max_length=120, verbose_name="Last_Name"),
        ),
    ]
