# Generated by Django 4.1 on 2023-03-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_alter_lead_first_name_alter_lead_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(default=True),
        ),
    ]
