# Generated by Django 4.1 on 2023-03-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_user_is_agent_user_is_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.agent",
                verbose_name="Agent Assigned",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a Agent",
                verbose_name="Agent",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user is a Organizer",
                verbose_name="Organizer",
            ),
        ),
    ]
