# Generated by Django 4.1 on 2023-03-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_alter_lead_agent_alter_user_is_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.userprofile",
            ),
            preserve_default=False,
        ),
    ]
