# Generated by Django 4.1 on 2023-03-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_category_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.userprofile"
            ),
        ),
    ]
