# Generated by Django 4.1 on 2023-03-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0009_alter_category_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="crm.category",
            ),
        ),
    ]
