# Generated by Django 4.1 on 2023-03-23 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0010_alter_lead_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Email Address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
